name: Deploy to development

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    name: Deploy to development
    environment: development
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Write something
        run: |
          echo ${{ jobs.environment }}
